# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/8"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "ansible", primary: "true" do |ansible|
    ansible.vm.provider "virtualbox" do |v|
      v.name = "ansible-master"
      v.memory = 1024
      v.cpus = 1
    end

    ansible.vm.network "private_network", ip: "192.168.56.20"
  end

  config.vm.define "web", primary: "true" do |web|
    web.vm.provider "virtualbox" do |v|
      v.name = "web-php-apache"
      v.memory = 1024
      v.cpus = 1
    end

    web.vm.network "forwarded_port", guest: 80, host: 8282, host_ip: "127.0.0.1"
    web.vm.network "private_network", ip: "192.168.56.30"
  end

  config.vm.define "db", primary: "true" do |db|
    db.vm.provider "virtualbox" do |v|
      v.name = "db-mysql"
      v.memory = 1024
      v.cpus = 1
    end

    db.vm.network "private_network", ip: "192.168.56.40"
  end
end
